version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ebin123}
      POSTGRES_DB: ${DB_NAME:-alsi}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-ebin123}@db:5432/${DB_NAME:-alsi}
      SECRET_KEY: ${SECRET_KEY:-yoursecretkeyhere}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
    volumes:
      - ./backend/static:/app/static
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
